//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:47:43 PM IST 
//


package com.micros.webservices.og._4_3.housekeeping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EndOfDayProjectionStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndOfDayProjectionStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinAvailableTonight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxOccupiedTonightRoom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxOccupiedTonightPersons" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxOccupiedTonightVIP" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxPertOccupiedTonight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MaxPertOccupiedTonightDayUse" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BlocksnotPickedUp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IndividualsRoom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IndividualsPersons" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IndividualsVIP" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GroupsandBlocksRoom" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GroupsandBlocksPersons" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GroupsandBlocksVIP" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RoomRevenue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="RoomRevenueAvg" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndOfDayProjectionStatus", propOrder = {
    "minAvailableTonight",
    "maxOccupiedTonightRoom",
    "maxOccupiedTonightPersons",
    "maxOccupiedTonightVIP",
    "maxPertOccupiedTonight",
    "maxPertOccupiedTonightDayUse",
    "blocksnotPickedUp",
    "individualsRoom",
    "individualsPersons",
    "individualsVIP",
    "groupsandBlocksRoom",
    "groupsandBlocksPersons",
    "groupsandBlocksVIP",
    "roomRevenue",
    "roomRevenueAvg"
})
public class EndOfDayProjectionStatus {

    @XmlElement(name = "MinAvailableTonight")
    protected Integer minAvailableTonight;
    @XmlElement(name = "MaxOccupiedTonightRoom")
    protected Integer maxOccupiedTonightRoom;
    @XmlElement(name = "MaxOccupiedTonightPersons")
    protected Integer maxOccupiedTonightPersons;
    @XmlElement(name = "MaxOccupiedTonightVIP")
    protected Integer maxOccupiedTonightVIP;
    @XmlElement(name = "MaxPertOccupiedTonight")
    protected Double maxPertOccupiedTonight;
    @XmlElement(name = "MaxPertOccupiedTonightDayUse")
    protected Double maxPertOccupiedTonightDayUse;
    @XmlElement(name = "BlocksnotPickedUp")
    protected Integer blocksnotPickedUp;
    @XmlElement(name = "IndividualsRoom")
    protected Integer individualsRoom;
    @XmlElement(name = "IndividualsPersons")
    protected Integer individualsPersons;
    @XmlElement(name = "IndividualsVIP")
    protected Integer individualsVIP;
    @XmlElement(name = "GroupsandBlocksRoom")
    protected Integer groupsandBlocksRoom;
    @XmlElement(name = "GroupsandBlocksPersons")
    protected Integer groupsandBlocksPersons;
    @XmlElement(name = "GroupsandBlocksVIP")
    protected Integer groupsandBlocksVIP;
    @XmlElement(name = "RoomRevenue")
    protected Double roomRevenue;
    @XmlElement(name = "RoomRevenueAvg")
    protected Double roomRevenueAvg;

    /**
     * Gets the value of the minAvailableTonight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinAvailableTonight() {
        return minAvailableTonight;
    }

    /**
     * Sets the value of the minAvailableTonight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinAvailableTonight(Integer value) {
        this.minAvailableTonight = value;
    }

    /**
     * Gets the value of the maxOccupiedTonightRoom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxOccupiedTonightRoom() {
        return maxOccupiedTonightRoom;
    }

    /**
     * Sets the value of the maxOccupiedTonightRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxOccupiedTonightRoom(Integer value) {
        this.maxOccupiedTonightRoom = value;
    }

    /**
     * Gets the value of the maxOccupiedTonightPersons property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxOccupiedTonightPersons() {
        return maxOccupiedTonightPersons;
    }

    /**
     * Sets the value of the maxOccupiedTonightPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxOccupiedTonightPersons(Integer value) {
        this.maxOccupiedTonightPersons = value;
    }

    /**
     * Gets the value of the maxOccupiedTonightVIP property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxOccupiedTonightVIP() {
        return maxOccupiedTonightVIP;
    }

    /**
     * Sets the value of the maxOccupiedTonightVIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxOccupiedTonightVIP(Integer value) {
        this.maxOccupiedTonightVIP = value;
    }

    /**
     * Gets the value of the maxPertOccupiedTonight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPertOccupiedTonight() {
        return maxPertOccupiedTonight;
    }

    /**
     * Sets the value of the maxPertOccupiedTonight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPertOccupiedTonight(Double value) {
        this.maxPertOccupiedTonight = value;
    }

    /**
     * Gets the value of the maxPertOccupiedTonightDayUse property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPertOccupiedTonightDayUse() {
        return maxPertOccupiedTonightDayUse;
    }

    /**
     * Sets the value of the maxPertOccupiedTonightDayUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPertOccupiedTonightDayUse(Double value) {
        this.maxPertOccupiedTonightDayUse = value;
    }

    /**
     * Gets the value of the blocksnotPickedUp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBlocksnotPickedUp() {
        return blocksnotPickedUp;
    }

    /**
     * Sets the value of the blocksnotPickedUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlocksnotPickedUp(Integer value) {
        this.blocksnotPickedUp = value;
    }

    /**
     * Gets the value of the individualsRoom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndividualsRoom() {
        return individualsRoom;
    }

    /**
     * Sets the value of the individualsRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndividualsRoom(Integer value) {
        this.individualsRoom = value;
    }

    /**
     * Gets the value of the individualsPersons property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndividualsPersons() {
        return individualsPersons;
    }

    /**
     * Sets the value of the individualsPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndividualsPersons(Integer value) {
        this.individualsPersons = value;
    }

    /**
     * Gets the value of the individualsVIP property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndividualsVIP() {
        return individualsVIP;
    }

    /**
     * Sets the value of the individualsVIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndividualsVIP(Integer value) {
        this.individualsVIP = value;
    }

    /**
     * Gets the value of the groupsandBlocksRoom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupsandBlocksRoom() {
        return groupsandBlocksRoom;
    }

    /**
     * Sets the value of the groupsandBlocksRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupsandBlocksRoom(Integer value) {
        this.groupsandBlocksRoom = value;
    }

    /**
     * Gets the value of the groupsandBlocksPersons property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupsandBlocksPersons() {
        return groupsandBlocksPersons;
    }

    /**
     * Sets the value of the groupsandBlocksPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupsandBlocksPersons(Integer value) {
        this.groupsandBlocksPersons = value;
    }

    /**
     * Gets the value of the groupsandBlocksVIP property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupsandBlocksVIP() {
        return groupsandBlocksVIP;
    }

    /**
     * Sets the value of the groupsandBlocksVIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupsandBlocksVIP(Integer value) {
        this.groupsandBlocksVIP = value;
    }

    /**
     * Gets the value of the roomRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRoomRevenue() {
        return roomRevenue;
    }

    /**
     * Sets the value of the roomRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRoomRevenue(Double value) {
        this.roomRevenue = value;
    }

    /**
     * Gets the value of the roomRevenueAvg property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRoomRevenueAvg() {
        return roomRevenueAvg;
    }

    /**
     * Sets the value of the roomRevenueAvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRoomRevenueAvg(Double value) {
        this.roomRevenueAvg = value;
    }

}
