//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:47:43 PM IST 
//


package com.micros.webservices.og._4_3.housekeeping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HouseKeepingDiscrepancy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HouseKeepingDiscrepancy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoomNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomStatus" type="{http://webservices.micros.com/og/4.3/HouseKeeping/}HouseKeepingRoomStatus" minOccurs="0"/>
 *         &lt;element name="HKStatus" type="{http://webservices.micros.com/og/4.3/HouseKeeping/}HouseKeepingFOStatus" minOccurs="0"/>
 *         &lt;element name="FOStatus" type="{http://webservices.micros.com/og/4.3/HouseKeeping/}HouseKeepingFOStatus" minOccurs="0"/>
 *         &lt;element name="ReservationStatus" type="{http://webservices.micros.com/og/4.3/HouseKeeping/}HouseKeepingReservationStatus" minOccurs="0"/>
 *         &lt;element name="FOPersons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HKPersons" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Discrepancy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HouseKeepingDiscrepancy", propOrder = {
    "roomNumber",
    "roomType",
    "roomStatus",
    "hkStatus",
    "foStatus",
    "reservationStatus",
    "foPersons",
    "hkPersons",
    "discrepancy"
})
public class HouseKeepingDiscrepancy {

    @XmlElement(name = "RoomNumber")
    protected String roomNumber;
    @XmlElement(name = "RoomType")
    protected String roomType;
    @XmlElement(name = "RoomStatus")
    @XmlSchemaType(name = "string")
    protected HouseKeepingRoomStatus roomStatus;
    @XmlElement(name = "HKStatus")
    @XmlSchemaType(name = "string")
    protected HouseKeepingFOStatus hkStatus;
    @XmlElement(name = "FOStatus")
    @XmlSchemaType(name = "string")
    protected HouseKeepingFOStatus foStatus;
    @XmlElement(name = "ReservationStatus")
    @XmlSchemaType(name = "string")
    protected HouseKeepingReservationStatus reservationStatus;
    @XmlElement(name = "FOPersons")
    protected String foPersons;
    @XmlElement(name = "HKPersons")
    protected Integer hkPersons;
    @XmlElement(name = "Discrepancy")
    protected String discrepancy;

    /**
     * Gets the value of the roomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomNumber(String value) {
        this.roomNumber = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomType(String value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the roomStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HouseKeepingRoomStatus }
     *     
     */
    public HouseKeepingRoomStatus getRoomStatus() {
        return roomStatus;
    }

    /**
     * Sets the value of the roomStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HouseKeepingRoomStatus }
     *     
     */
    public void setRoomStatus(HouseKeepingRoomStatus value) {
        this.roomStatus = value;
    }

    /**
     * Gets the value of the hkStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HouseKeepingFOStatus }
     *     
     */
    public HouseKeepingFOStatus getHKStatus() {
        return hkStatus;
    }

    /**
     * Sets the value of the hkStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HouseKeepingFOStatus }
     *     
     */
    public void setHKStatus(HouseKeepingFOStatus value) {
        this.hkStatus = value;
    }

    /**
     * Gets the value of the foStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HouseKeepingFOStatus }
     *     
     */
    public HouseKeepingFOStatus getFOStatus() {
        return foStatus;
    }

    /**
     * Sets the value of the foStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HouseKeepingFOStatus }
     *     
     */
    public void setFOStatus(HouseKeepingFOStatus value) {
        this.foStatus = value;
    }

    /**
     * Gets the value of the reservationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HouseKeepingReservationStatus }
     *     
     */
    public HouseKeepingReservationStatus getReservationStatus() {
        return reservationStatus;
    }

    /**
     * Sets the value of the reservationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HouseKeepingReservationStatus }
     *     
     */
    public void setReservationStatus(HouseKeepingReservationStatus value) {
        this.reservationStatus = value;
    }

    /**
     * Gets the value of the foPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOPersons() {
        return foPersons;
    }

    /**
     * Sets the value of the foPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOPersons(String value) {
        this.foPersons = value;
    }

    /**
     * Gets the value of the hkPersons property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHKPersons() {
        return hkPersons;
    }

    /**
     * Sets the value of the hkPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHKPersons(Integer value) {
        this.hkPersons = value;
    }

    /**
     * Gets the value of the discrepancy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscrepancy() {
        return discrepancy;
    }

    /**
     * Sets the value of the discrepancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscrepancy(String value) {
        this.discrepancy = value;
    }

}
