//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:47:43 PM IST 
//


package com.micros.webservices.og._4_3.housekeeping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HouseKeepingStatusList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HouseKeepingStatusList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HouseKeepingStatus" type="{http://webservices.micros.com/og/4.3/HouseKeeping/}HouseKeepingStatus" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HouseKeepingStatusList", propOrder = {
    "houseKeepingStatus"
})
public class HouseKeepingStatusList {

    @XmlElement(name = "HouseKeepingStatus")
    protected List<HouseKeepingStatus> houseKeepingStatus;

    /**
     * Gets the value of the houseKeepingStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the houseKeepingStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHouseKeepingStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HouseKeepingStatus }
     * 
     * 
     */
    public List<HouseKeepingStatus> getHouseKeepingStatus() {
        if (houseKeepingStatus == null) {
            houseKeepingStatus = new ArrayList<HouseKeepingStatus>();
        }
        return this.houseKeepingStatus;
    }

}
