//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:47:43 PM IST 
//


package com.micros.webservices.og._4_3.housekeeping;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HouseKeepingReservationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HouseKeepingReservationStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STAYOVER"/>
 *     &lt;enumeration value="ARRIVED"/>
 *     &lt;enumeration value="DUEOUT"/>
 *     &lt;enumeration value="DEPARTURES"/>
 *     &lt;enumeration value="DEPARTED"/>
 *     &lt;enumeration value="ARRIVAL"/>
 *     &lt;enumeration value="EXPECTED"/>
 *     &lt;enumeration value="RESERVED"/>
 *     &lt;enumeration value="DAYUSE"/>
 *     &lt;enumeration value="ARRIVEDANDSTAYOVER"/>
 *     &lt;enumeration value="VACANT"/>
 *     &lt;enumeration value="NOTRESERVED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HouseKeepingReservationStatus")
@XmlEnum
public enum HouseKeepingReservationStatus {

    STAYOVER,
    ARRIVED,
    DUEOUT,
    DEPARTURES,
    DEPARTED,
    ARRIVAL,
    EXPECTED,
    RESERVED,
    DAYUSE,
    ARRIVEDANDSTAYOVER,
    VACANT,
    NOTRESERVED;

    public String value() {
        return name();
    }

    public static HouseKeepingReservationStatus fromValue(String v) {
        return valueOf(v);
    }

}
