//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:48:57 PM IST 
//


package com.micros.webservices.og._4_3.meetingroom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.hotelcommon.HotelReference;


/**
 * <p>Java class for BlockDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlockDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BlockData" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}BlockType"/>
 *         &lt;element name="HotelReference" type="{http://webservices.micros.com/og/4.3/HotelCommon/}HotelReference"/>
 *         &lt;element name="BookedPackageEvent" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}BookedPackageEvent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SleepingRooms" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}SleepingRoom" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RevenueSummary" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}Revenue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlockDetails", propOrder = {
    "blockData",
    "hotelReference",
    "bookedPackageEvent",
    "sleepingRooms",
    "revenueSummary"
})
public class BlockDetails {

    @XmlElement(name = "BlockData", required = true)
    protected BlockType blockData;
    @XmlElement(name = "HotelReference", required = true)
    protected HotelReference hotelReference;
    @XmlElement(name = "BookedPackageEvent")
    protected List<BookedPackageEvent> bookedPackageEvent;
    @XmlElement(name = "SleepingRooms")
    protected List<SleepingRoom> sleepingRooms;
    @XmlElement(name = "RevenueSummary")
    protected Revenue revenueSummary;

    /**
     * Gets the value of the blockData property.
     * 
     * @return
     *     possible object is
     *     {@link BlockType }
     *     
     */
    public BlockType getBlockData() {
        return blockData;
    }

    /**
     * Sets the value of the blockData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockType }
     *     
     */
    public void setBlockData(BlockType value) {
        this.blockData = value;
    }

    /**
     * Gets the value of the hotelReference property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReference }
     *     
     */
    public HotelReference getHotelReference() {
        return hotelReference;
    }

    /**
     * Sets the value of the hotelReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReference }
     *     
     */
    public void setHotelReference(HotelReference value) {
        this.hotelReference = value;
    }

    /**
     * Gets the value of the bookedPackageEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookedPackageEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBookedPackageEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookedPackageEvent }
     * 
     * 
     */
    public List<BookedPackageEvent> getBookedPackageEvent() {
        if (bookedPackageEvent == null) {
            bookedPackageEvent = new ArrayList<BookedPackageEvent>();
        }
        return this.bookedPackageEvent;
    }

    /**
     * Gets the value of the sleepingRooms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sleepingRooms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSleepingRooms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SleepingRoom }
     * 
     * 
     */
    public List<SleepingRoom> getSleepingRooms() {
        if (sleepingRooms == null) {
            sleepingRooms = new ArrayList<SleepingRoom>();
        }
        return this.sleepingRooms;
    }

    /**
     * Gets the value of the revenueSummary property.
     * 
     * @return
     *     possible object is
     *     {@link Revenue }
     *     
     */
    public Revenue getRevenueSummary() {
        return revenueSummary;
    }

    /**
     * Sets the value of the revenueSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Revenue }
     *     
     */
    public void setRevenueSummary(Revenue value) {
        this.revenueSummary = value;
    }

}
