//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:48:57 PM IST 
//


package com.micros.webservices.og._4_3.meetingroom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BookedPackage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookedPackage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Packages" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}Package"/>
 *         &lt;element name="PackageAddons" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}PackageAddon" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookedPackage", propOrder = {
    "packages",
    "packageAddons"
})
public class BookedPackage {

    @XmlElement(name = "Packages", required = true)
    protected Package packages;
    @XmlElement(name = "PackageAddons")
    protected PackageAddon packageAddons;

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link Package }
     *     
     */
    public Package getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Package }
     *     
     */
    public void setPackages(Package value) {
        this.packages = value;
    }

    /**
     * Gets the value of the packageAddons property.
     * 
     * @return
     *     possible object is
     *     {@link PackageAddon }
     *     
     */
    public PackageAddon getPackageAddons() {
        return packageAddons;
    }

    /**
     * Sets the value of the packageAddons property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageAddon }
     *     
     */
    public void setPackageAddons(PackageAddon value) {
        this.packageAddons = value;
    }

}
