//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:48:57 PM IST 
//


package com.micros.webservices.og._4_3.meetingroom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.InternalID;
import com.micros.webservices.og._4_3.hotelcommon.TimeSpan;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MiscellaneousItems" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}MiscellaneousItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Menus" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}Menu" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FunctionSpace" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}FunctionSpace"/>
 *         &lt;element name="EventID" type="{http://webservices.micros.com/og/4.3/Common/}InternalID" minOccurs="0"/>
 *         &lt;element name="EventDate" type="{http://webservices.micros.com/og/4.3/HotelCommon/}TimeSpan" minOccurs="0"/>
 *         &lt;element name="Delegates" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}Delegate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="registrationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="openForRegistration" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="numberOfAttendees" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="numberOfRegisteredAttendees" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "miscellaneousItems",
    "menus",
    "functionSpace",
    "eventID",
    "eventDate",
    "delegates"
})
@XmlSeeAlso({
    com.micros.webservices.og._4_3.meetingroom.Package.Events.class
})
public class Event {

    @XmlElement(name = "MiscellaneousItems")
    protected List<MiscellaneousItem> miscellaneousItems;
    @XmlElement(name = "Menus")
    protected List<Menu> menus;
    @XmlElement(name = "FunctionSpace", required = true)
    protected FunctionSpace functionSpace;
    @XmlElement(name = "EventID")
    protected InternalID eventID;
    @XmlElement(name = "EventDate")
    protected TimeSpan eventDate;
    @XmlElement(name = "Delegates")
    protected List<Delegate> delegates;
    @XmlAttribute(name = "registrationRequired")
    protected Boolean registrationRequired;
    @XmlAttribute(name = "openForRegistration")
    protected Boolean openForRegistration;
    @XmlAttribute(name = "numberOfAttendees")
    protected Integer numberOfAttendees;
    @XmlAttribute(name = "numberOfRegisteredAttendees")
    protected Integer numberOfRegisteredAttendees;

    /**
     * Gets the value of the miscellaneousItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscellaneousItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscellaneousItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MiscellaneousItem }
     * 
     * 
     */
    public List<MiscellaneousItem> getMiscellaneousItems() {
        if (miscellaneousItems == null) {
            miscellaneousItems = new ArrayList<MiscellaneousItem>();
        }
        return this.miscellaneousItems;
    }

    /**
     * Gets the value of the menus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Menu }
     * 
     * 
     */
    public List<Menu> getMenus() {
        if (menus == null) {
            menus = new ArrayList<Menu>();
        }
        return this.menus;
    }

    /**
     * Gets the value of the functionSpace property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionSpace }
     *     
     */
    public FunctionSpace getFunctionSpace() {
        return functionSpace;
    }

    /**
     * Sets the value of the functionSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionSpace }
     *     
     */
    public void setFunctionSpace(FunctionSpace value) {
        this.functionSpace = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link InternalID }
     *     
     */
    public InternalID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalID }
     *     
     */
    public void setEventID(InternalID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the eventDate property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getEventDate() {
        return eventDate;
    }

    /**
     * Sets the value of the eventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setEventDate(TimeSpan value) {
        this.eventDate = value;
    }

    /**
     * Gets the value of the delegates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delegates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelegates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delegate }
     * 
     * 
     */
    public List<Delegate> getDelegates() {
        if (delegates == null) {
            delegates = new ArrayList<Delegate>();
        }
        return this.delegates;
    }

    /**
     * Gets the value of the registrationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegistrationRequired() {
        return registrationRequired;
    }

    /**
     * Sets the value of the registrationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegistrationRequired(Boolean value) {
        this.registrationRequired = value;
    }

    /**
     * Gets the value of the openForRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOpenForRegistration() {
        return openForRegistration;
    }

    /**
     * Sets the value of the openForRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpenForRegistration(Boolean value) {
        this.openForRegistration = value;
    }

    /**
     * Gets the value of the numberOfAttendees property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfAttendees() {
        return numberOfAttendees;
    }

    /**
     * Sets the value of the numberOfAttendees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfAttendees(Integer value) {
        this.numberOfAttendees = value;
    }

    /**
     * Gets the value of the numberOfRegisteredAttendees property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfRegisteredAttendees() {
        return numberOfRegisteredAttendees;
    }

    /**
     * Sets the value of the numberOfRegisteredAttendees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfRegisteredAttendees(Integer value) {
        this.numberOfRegisteredAttendees = value;
    }

}
