//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:48:57 PM IST 
//


package com.micros.webservices.og._4_3.meetingroom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.InternalID;
import com.micros.webservices.og._4_3.hotelcommon.TimeSpan;


/**
 * <p>Java class for MeetingEventBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeetingEventBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventDate" type="{http://webservices.micros.com/og/4.3/HotelCommon/}TimeSpan"/>
 *         &lt;element name="EventID" type="{http://webservices.micros.com/og/4.3/Common/}InternalID" minOccurs="0"/>
 *         &lt;element name="FunctionSpace" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}FunctionSpace" minOccurs="0"/>
 *         &lt;element name="MiscellaneousItems" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}MiscellaneousItem">
 *                 &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="addon" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Menus" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}Menu">
 *                 &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MenuItems" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}MenuItem">
 *                 &lt;attribute name="menuID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="bookedMenuID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Delegates" type="{http://webservices.micros.com/og/4.3/MeetingRoom/}Delegate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eventType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numberOfAttendees" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="registrationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="openForRegistration" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="numberOfRegisteredAttendees" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeetingEventBase", propOrder = {
    "eventDate",
    "eventID",
    "functionSpace",
    "miscellaneousItems",
    "menus",
    "menuItems",
    "delegates"
})
public class MeetingEventBase {

    @XmlElement(name = "EventDate", required = true)
    protected TimeSpan eventDate;
    @XmlElement(name = "EventID")
    protected InternalID eventID;
    @XmlElement(name = "FunctionSpace")
    protected FunctionSpace functionSpace;
    @XmlElement(name = "MiscellaneousItems")
    protected List<MeetingEventBase.MiscellaneousItems> miscellaneousItems;
    @XmlElement(name = "Menus")
    protected List<MeetingEventBase.Menus> menus;
    @XmlElement(name = "MenuItems")
    protected List<MeetingEventBase.MenuItems> menuItems;
    @XmlElement(name = "Delegates")
    protected List<Delegate> delegates;
    @XmlAttribute(name = "eventType")
    protected String eventType;
    @XmlAttribute(name = "numberOfAttendees", required = true)
    protected int numberOfAttendees;
    @XmlAttribute(name = "registrationRequired")
    protected Boolean registrationRequired;
    @XmlAttribute(name = "openForRegistration")
    protected Boolean openForRegistration;
    @XmlAttribute(name = "numberOfRegisteredAttendees")
    protected Integer numberOfRegisteredAttendees;

    /**
     * Gets the value of the eventDate property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getEventDate() {
        return eventDate;
    }

    /**
     * Sets the value of the eventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setEventDate(TimeSpan value) {
        this.eventDate = value;
    }

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link InternalID }
     *     
     */
    public InternalID getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalID }
     *     
     */
    public void setEventID(InternalID value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the functionSpace property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionSpace }
     *     
     */
    public FunctionSpace getFunctionSpace() {
        return functionSpace;
    }

    /**
     * Sets the value of the functionSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionSpace }
     *     
     */
    public void setFunctionSpace(FunctionSpace value) {
        this.functionSpace = value;
    }

    /**
     * Gets the value of the miscellaneousItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscellaneousItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscellaneousItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeetingEventBase.MiscellaneousItems }
     * 
     * 
     */
    public List<MeetingEventBase.MiscellaneousItems> getMiscellaneousItems() {
        if (miscellaneousItems == null) {
            miscellaneousItems = new ArrayList<MeetingEventBase.MiscellaneousItems>();
        }
        return this.miscellaneousItems;
    }

    /**
     * Gets the value of the menus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeetingEventBase.Menus }
     * 
     * 
     */
    public List<MeetingEventBase.Menus> getMenus() {
        if (menus == null) {
            menus = new ArrayList<MeetingEventBase.Menus>();
        }
        return this.menus;
    }

    /**
     * Gets the value of the menuItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the menuItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMenuItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeetingEventBase.MenuItems }
     * 
     * 
     */
    public List<MeetingEventBase.MenuItems> getMenuItems() {
        if (menuItems == null) {
            menuItems = new ArrayList<MeetingEventBase.MenuItems>();
        }
        return this.menuItems;
    }

    /**
     * Gets the value of the delegates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delegates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelegates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delegate }
     * 
     * 
     */
    public List<Delegate> getDelegates() {
        if (delegates == null) {
            delegates = new ArrayList<Delegate>();
        }
        return this.delegates;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the numberOfAttendees property.
     * 
     */
    public int getNumberOfAttendees() {
        return numberOfAttendees;
    }

    /**
     * Sets the value of the numberOfAttendees property.
     * 
     */
    public void setNumberOfAttendees(int value) {
        this.numberOfAttendees = value;
    }

    /**
     * Gets the value of the registrationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegistrationRequired() {
        return registrationRequired;
    }

    /**
     * Sets the value of the registrationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegistrationRequired(Boolean value) {
        this.registrationRequired = value;
    }

    /**
     * Gets the value of the openForRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOpenForRegistration() {
        return openForRegistration;
    }

    /**
     * Sets the value of the openForRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpenForRegistration(Boolean value) {
        this.openForRegistration = value;
    }

    /**
     * Gets the value of the numberOfRegisteredAttendees property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfRegisteredAttendees() {
        return numberOfRegisteredAttendees;
    }

    /**
     * Sets the value of the numberOfRegisteredAttendees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfRegisteredAttendees(Integer value) {
        this.numberOfRegisteredAttendees = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}MenuItem">
     *       &lt;attribute name="menuID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="bookedMenuID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MenuItems
        extends MenuItem
    {

        @XmlAttribute(name = "menuID", required = true)
        protected int menuID;
        @XmlAttribute(name = "quantity", required = true)
        protected int quantity;
        @XmlAttribute(name = "bookedMenuID")
        protected Integer bookedMenuID;

        /**
         * Gets the value of the menuID property.
         * 
         */
        public int getMenuID() {
            return menuID;
        }

        /**
         * Sets the value of the menuID property.
         * 
         */
        public void setMenuID(int value) {
            this.menuID = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the bookedMenuID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBookedMenuID() {
            return bookedMenuID;
        }

        /**
         * Sets the value of the bookedMenuID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBookedMenuID(Integer value) {
            this.bookedMenuID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}Menu">
     *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Menus
        extends Menu
    {

        @XmlAttribute(name = "quantity", required = true)
        protected int quantity;

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://webservices.micros.com/og/4.3/MeetingRoom/}MiscellaneousItem">
     *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="addon" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MiscellaneousItems
        extends MiscellaneousItem
    {

        @XmlAttribute(name = "quantity", required = true)
        protected int quantity;
        @XmlAttribute(name = "addon")
        protected Boolean addon;

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the addon property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAddon() {
            return addon;
        }

        /**
         * Sets the value of the addon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAddon(Boolean value) {
            this.addon = value;
        }

    }

}
