//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.membership;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.Membership;
import com.micros.webservices.og._4_3.name.Profile;


/**
 * <p>Java class for EnrollmentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnrollmentInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Profile" type="{http://webservices.micros.com/og/4.3/Name/}Profile"/>
 *         &lt;element name="Membership" type="{http://webservices.micros.com/og/4.3/Common/}Membership" minOccurs="0"/>
 *         &lt;element name="Fee" type="{http://webservices.micros.com/og/4.3/Membership/}Fee" minOccurs="0"/>
 *         &lt;element name="EnrollmentAction" type="{http://webservices.micros.com/og/4.3/Membership/}EnrollmentActions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnrollmentInfo", propOrder = {
    "profile",
    "membership",
    "fee",
    "enrollmentAction"
})
public class EnrollmentInfo {

    @XmlElement(name = "Profile", required = true)
    protected Profile profile;
    @XmlElement(name = "Membership")
    protected Membership membership;
    @XmlElement(name = "Fee")
    protected Fee fee;
    @XmlElement(name = "EnrollmentAction", required = true)
    @XmlSchemaType(name = "string")
    protected EnrollmentActions enrollmentAction;

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link Profile }
     *     
     */
    public Profile getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile }
     *     
     */
    public void setProfile(Profile value) {
        this.profile = value;
    }

    /**
     * Gets the value of the membership property.
     * 
     * @return
     *     possible object is
     *     {@link Membership }
     *     
     */
    public Membership getMembership() {
        return membership;
    }

    /**
     * Sets the value of the membership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Membership }
     *     
     */
    public void setMembership(Membership value) {
        this.membership = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return
     *     possible object is
     *     {@link Fee }
     *     
     */
    public Fee getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fee }
     *     
     */
    public void setFee(Fee value) {
        this.fee = value;
    }

    /**
     * Gets the value of the enrollmentAction property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentActions }
     *     
     */
    public EnrollmentActions getEnrollmentAction() {
        return enrollmentAction;
    }

    /**
     * Sets the value of the enrollmentAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentActions }
     *     
     */
    public void setEnrollmentAction(EnrollmentActions value) {
        this.enrollmentAction = value;
    }

}
