//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.membership;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.micros.webservices.og._4_3.membership package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.micros.webservices.og._4_3.membership
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MemberSearchCriteria }
     * 
     */
    public MemberSearchCriteria createMemberSearchCriteria() {
        return new MemberSearchCriteria();
    }

    /**
     * Create an instance of {@link FetchMemberTierWizardResponse }
     * 
     */
    public FetchMemberTierWizardResponse createFetchMemberTierWizardResponse() {
        return new FetchMemberTierWizardResponse();
    }

    /**
     * Create an instance of {@link TierWizard }
     * 
     */
    public TierWizard createTierWizard() {
        return new TierWizard();
    }

    /**
     * Create an instance of {@link AddBenefitResponse }
     * 
     */
    public AddBenefitResponse createAddBenefitResponse() {
        return new AddBenefitResponse();
    }

    /**
     * Create an instance of {@link FetchMemberTierWizardRequest }
     * 
     */
    public FetchMemberTierWizardRequest createFetchMemberTierWizardRequest() {
        return new FetchMemberTierWizardRequest();
    }

    /**
     * Create an instance of {@link FetchBenefitsRequest }
     * 
     */
    public FetchBenefitsRequest createFetchBenefitsRequest() {
        return new FetchBenefitsRequest();
    }

    /**
     * Create an instance of {@link FetchBenefitsResponse }
     * 
     */
    public FetchBenefitsResponse createFetchBenefitsResponse() {
        return new FetchBenefitsResponse();
    }

    /**
     * Create an instance of {@link Benefit }
     * 
     */
    public Benefit createBenefit() {
        return new Benefit();
    }

    /**
     * Create an instance of {@link AddBenefitRequest }
     * 
     */
    public AddBenefitRequest createAddBenefitRequest() {
        return new AddBenefitRequest();
    }

    /**
     * Create an instance of {@link PointsInfo }
     * 
     */
    public PointsInfo createPointsInfo() {
        return new PointsInfo();
    }

    /**
     * Create an instance of {@link RateAward }
     * 
     */
    public RateAward createRateAward() {
        return new RateAward();
    }

    /**
     * Create an instance of {@link AwardInformationList }
     * 
     */
    public AwardInformationList createAwardInformationList() {
        return new AwardInformationList();
    }

    /**
     * Create an instance of {@link MemberRevenue }
     * 
     */
    public MemberRevenue createMemberRevenue() {
        return new MemberRevenue();
    }

    /**
     * Create an instance of {@link StayPointsInfo }
     * 
     */
    public StayPointsInfo createStayPointsInfo() {
        return new StayPointsInfo();
    }

    /**
     * Create an instance of {@link StatementReference }
     * 
     */
    public StatementReference createStatementReference() {
        return new StatementReference();
    }

    /**
     * Create an instance of {@link ProductAwardList }
     * 
     */
    public ProductAwardList createProductAwardList() {
        return new ProductAwardList();
    }

    /**
     * Create an instance of {@link TierPointsInfo }
     * 
     */
    public TierPointsInfo createTierPointsInfo() {
        return new TierPointsInfo();
    }

    /**
     * Create an instance of {@link UDFDate }
     * 
     */
    public UDFDate createUDFDate() {
        return new UDFDate();
    }

    /**
     * Create an instance of {@link StatementReferenceList }
     * 
     */
    public StatementReferenceList createStatementReferenceList() {
        return new StatementReferenceList();
    }

    /**
     * Create an instance of {@link UDFs }
     * 
     */
    public UDFs createUDFs() {
        return new UDFs();
    }

    /**
     * Create an instance of {@link AwardInformation }
     * 
     */
    public AwardInformation createAwardInformation() {
        return new AwardInformation();
    }

    /**
     * Create an instance of {@link PointsChangeList }
     * 
     */
    public PointsChangeList createPointsChangeList() {
        return new PointsChangeList();
    }

    /**
     * Create an instance of {@link RateAwardList }
     * 
     */
    public RateAwardList createRateAwardList() {
        return new RateAwardList();
    }

    /**
     * Create an instance of {@link Tsc }
     * 
     */
    public Tsc createTsc() {
        return new Tsc();
    }

    /**
     * Create an instance of {@link FeeList }
     * 
     */
    public FeeList createFeeList() {
        return new FeeList();
    }

    /**
     * Create an instance of {@link RequiredPointsInfo }
     * 
     */
    public RequiredPointsInfo createRequiredPointsInfo() {
        return new RequiredPointsInfo();
    }

    /**
     * Create an instance of {@link UDFCharacter }
     * 
     */
    public UDFCharacter createUDFCharacter() {
        return new UDFCharacter();
    }

    /**
     * Create an instance of {@link UDFsList }
     * 
     */
    public UDFsList createUDFsList() {
        return new UDFsList();
    }

    /**
     * Create an instance of {@link MemberPointsList }
     * 
     */
    public MemberPointsList createMemberPointsList() {
        return new MemberPointsList();
    }

    /**
     * Create an instance of {@link UpgradeAward }
     * 
     */
    public UpgradeAward createUpgradeAward() {
        return new UpgradeAward();
    }

    /**
     * Create an instance of {@link ECertificate }
     * 
     */
    public ECertificate createECertificate() {
        return new ECertificate();
    }

    /**
     * Create an instance of {@link PromotionDetails }
     * 
     */
    public PromotionDetails createPromotionDetails() {
        return new PromotionDetails();
    }

    /**
     * Create an instance of {@link PointsSchedule }
     * 
     */
    public PointsSchedule createPointsSchedule() {
        return new PointsSchedule();
    }

    /**
     * Create an instance of {@link FeeHistoryList }
     * 
     */
    public FeeHistoryList createFeeHistoryList() {
        return new FeeHistoryList();
    }

    /**
     * Create an instance of {@link MembershipTransactionList }
     * 
     */
    public MembershipTransactionList createMembershipTransactionList() {
        return new MembershipTransactionList();
    }

    /**
     * Create an instance of {@link TransactionPointsInfo }
     * 
     */
    public TransactionPointsInfo createTransactionPointsInfo() {
        return new TransactionPointsInfo();
    }

    /**
     * Create an instance of {@link PointsBreakup }
     * 
     */
    public PointsBreakup createPointsBreakup() {
        return new PointsBreakup();
    }

    /**
     * Create an instance of {@link TransactionAward }
     * 
     */
    public TransactionAward createTransactionAward() {
        return new TransactionAward();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link ProductAward }
     * 
     */
    public ProductAward createProductAward() {
        return new ProductAward();
    }

    /**
     * Create an instance of {@link ProfilePromotion }
     * 
     */
    public ProfilePromotion createProfilePromotion() {
        return new ProfilePromotion();
    }

    /**
     * Create an instance of {@link FeeHistoryInfo }
     * 
     */
    public FeeHistoryInfo createFeeHistoryInfo() {
        return new FeeHistoryInfo();
    }

    /**
     * Create an instance of {@link EnrollmentInfo }
     * 
     */
    public EnrollmentInfo createEnrollmentInfo() {
        return new EnrollmentInfo();
    }

    /**
     * Create an instance of {@link Points }
     * 
     */
    public Points createPoints() {
        return new Points();
    }

    /**
     * Create an instance of {@link ProfilePromotionList }
     * 
     */
    public ProfilePromotionList createProfilePromotionList() {
        return new ProfilePromotionList();
    }

    /**
     * Create an instance of {@link IssueTransactionAwardDetails }
     * 
     */
    public IssueTransactionAwardDetails createIssueTransactionAwardDetails() {
        return new IssueTransactionAwardDetails();
    }

    /**
     * Create an instance of {@link RevenueList }
     * 
     */
    public RevenueList createRevenueList() {
        return new RevenueList();
    }

    /**
     * Create an instance of {@link Statement }
     * 
     */
    public Statement createStatement() {
        return new Statement();
    }

    /**
     * Create an instance of {@link Fee }
     * 
     */
    public Fee createFee() {
        return new Fee();
    }

    /**
     * Create an instance of {@link UpgradeAwardList }
     * 
     */
    public UpgradeAwardList createUpgradeAwardList() {
        return new UpgradeAwardList();
    }

    /**
     * Create an instance of {@link UDFNumeric }
     * 
     */
    public UDFNumeric createUDFNumeric() {
        return new UDFNumeric();
    }

    /**
     * Create an instance of {@link FavoriteGuestList }
     * 
     */
    public FavoriteGuestList createFavoriteGuestList() {
        return new FavoriteGuestList();
    }

    /**
     * Create an instance of {@link TransactionAwardList }
     * 
     */
    public TransactionAwardList createTransactionAwardList() {
        return new TransactionAwardList();
    }

    /**
     * Create an instance of {@link MembershipTransaction }
     * 
     */
    public MembershipTransaction createMembershipTransaction() {
        return new MembershipTransaction();
    }

    /**
     * Create an instance of {@link PointsBreakupList }
     * 
     */
    public PointsBreakupList createPointsBreakupList() {
        return new PointsBreakupList();
    }

    /**
     * Create an instance of {@link RequiredPointList }
     * 
     */
    public RequiredPointList createRequiredPointList() {
        return new RequiredPointList();
    }

    /**
     * Create an instance of {@link PromotionSubscription }
     * 
     */
    public PromotionSubscription createPromotionSubscription() {
        return new PromotionSubscription();
    }

    /**
     * Create an instance of {@link Award }
     * 
     */
    public Award createAward() {
        return new Award();
    }

    /**
     * Create an instance of {@link PointsChange }
     * 
     */
    public PointsChange createPointsChange() {
        return new PointsChange();
    }

    /**
     * Create an instance of {@link PromotionSubscriptionList }
     * 
     */
    public PromotionSubscriptionList createPromotionSubscriptionList() {
        return new PromotionSubscriptionList();
    }

    /**
     * Create an instance of {@link AwardPointsInfo }
     * 
     */
    public AwardPointsInfo createAwardPointsInfo() {
        return new AwardPointsInfo();
    }

    /**
     * Create an instance of {@link RuleSchedule }
     * 
     */
    public RuleSchedule createRuleSchedule() {
        return new RuleSchedule();
    }

    /**
     * Create an instance of {@link FavoriteGuest }
     * 
     */
    public FavoriteGuest createFavoriteGuest() {
        return new FavoriteGuest();
    }

    /**
     * Create an instance of {@link ECertificateList }
     * 
     */
    public ECertificateList createECertificateList() {
        return new ECertificateList();
    }

    /**
     * Create an instance of {@link MemberSearchCriteria.Membership }
     * 
     */
    public MemberSearchCriteria.Membership createMemberSearchCriteriaMembership() {
        return new MemberSearchCriteria.Membership();
    }

}
