//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.membership;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointsBreakup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointsBreakup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pointsType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="points" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="pointsDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointsBreakup")
public class PointsBreakup {

    @XmlAttribute(name = "pointsType")
    protected String pointsType;
    @XmlAttribute(name = "points", required = true)
    protected double points;
    @XmlAttribute(name = "pointsDescription")
    protected String pointsDescription;

    /**
     * Gets the value of the pointsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsType() {
        return pointsType;
    }

    /**
     * Sets the value of the pointsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsType(String value) {
        this.pointsType = value;
    }

    /**
     * Gets the value of the points property.
     * 
     */
    public double getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     */
    public void setPoints(double value) {
        this.points = value;
    }

    /**
     * Gets the value of the pointsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsDescription() {
        return pointsDescription;
    }

    /**
     * Sets the value of the pointsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsDescription(String value) {
        this.pointsDescription = value;
    }

}
