//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.membership;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointsInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AwardPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}AwardPointsInfo" minOccurs="0"/>
 *         &lt;element name="TierPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}TierPointsInfo" minOccurs="0"/>
 *         &lt;element name="StayPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}StayPointsInfo" minOccurs="0"/>
 *         &lt;element name="TransactionPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}TransactionPointsInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointsInfo", propOrder = {
    "awardPointsInfo",
    "tierPointsInfo",
    "stayPointsInfo",
    "transactionPointsInfo"
})
public class PointsInfo {

    @XmlElement(name = "AwardPointsInfo")
    protected AwardPointsInfo awardPointsInfo;
    @XmlElement(name = "TierPointsInfo")
    protected TierPointsInfo tierPointsInfo;
    @XmlElement(name = "StayPointsInfo")
    protected StayPointsInfo stayPointsInfo;
    @XmlElement(name = "TransactionPointsInfo")
    protected TransactionPointsInfo transactionPointsInfo;

    /**
     * Gets the value of the awardPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AwardPointsInfo }
     *     
     */
    public AwardPointsInfo getAwardPointsInfo() {
        return awardPointsInfo;
    }

    /**
     * Sets the value of the awardPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardPointsInfo }
     *     
     */
    public void setAwardPointsInfo(AwardPointsInfo value) {
        this.awardPointsInfo = value;
    }

    /**
     * Gets the value of the tierPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TierPointsInfo }
     *     
     */
    public TierPointsInfo getTierPointsInfo() {
        return tierPointsInfo;
    }

    /**
     * Sets the value of the tierPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TierPointsInfo }
     *     
     */
    public void setTierPointsInfo(TierPointsInfo value) {
        this.tierPointsInfo = value;
    }

    /**
     * Gets the value of the stayPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link StayPointsInfo }
     *     
     */
    public StayPointsInfo getStayPointsInfo() {
        return stayPointsInfo;
    }

    /**
     * Sets the value of the stayPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayPointsInfo }
     *     
     */
    public void setStayPointsInfo(StayPointsInfo value) {
        this.stayPointsInfo = value;
    }

    /**
     * Gets the value of the transactionPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionPointsInfo }
     *     
     */
    public TransactionPointsInfo getTransactionPointsInfo() {
        return transactionPointsInfo;
    }

    /**
     * Sets the value of the transactionPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionPointsInfo }
     *     
     */
    public void setTransactionPointsInfo(TransactionPointsInfo value) {
        this.transactionPointsInfo = value;
    }

}
