//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:48:57 PM IST 
//


package com.micros.webservices.og._4_3.availability;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.hotelcommon.PropertyStatusCodeType;


/**
 * <p>Java class for PropertyStatusCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyStatusCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyLevelError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="propertyStatusCode" use="required" type="{http://webservices.micros.com/og/4.3/HotelCommon/}PropertyStatusCodeType" />
 *       &lt;attribute name="otherPropertyStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyStatusCode", propOrder = {
    "propertyLevelError"
})
public class PropertyStatusCode {

    @XmlElement(name = "PropertyLevelError")
    protected String propertyLevelError;
    @XmlAttribute(name = "propertyStatusCode", required = true)
    protected PropertyStatusCodeType propertyStatusCode;
    @XmlAttribute(name = "otherPropertyStatusCode")
    protected String otherPropertyStatusCode;

    /**
     * Gets the value of the propertyLevelError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyLevelError() {
        return propertyLevelError;
    }

    /**
     * Sets the value of the propertyLevelError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyLevelError(String value) {
        this.propertyLevelError = value;
    }

    /**
     * Gets the value of the propertyStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyStatusCodeType }
     *     
     */
    public PropertyStatusCodeType getPropertyStatusCode() {
        return propertyStatusCode;
    }

    /**
     * Sets the value of the propertyStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyStatusCodeType }
     *     
     */
    public void setPropertyStatusCode(PropertyStatusCodeType value) {
        this.propertyStatusCode = value;
    }

    /**
     * Gets the value of the otherPropertyStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherPropertyStatusCode() {
        return otherPropertyStatusCode;
    }

    /**
     * Sets the value of the otherPropertyStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherPropertyStatusCode(String value) {
        this.otherPropertyStatusCode = value;
    }

}
