//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:53:11 PM IST 
//


package com.micros.webservices.og._4_3.security;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.micros.webservices.og._4_3.security package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.micros.webservices.og._4_3.security
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserProfile }
     * 
     */
    public UserProfile createUserProfile() {
        return new UserProfile();
    }

    /**
     * Create an instance of {@link UserGroupItem }
     * 
     */
    public UserGroupItem createUserGroupItem() {
        return new UserGroupItem();
    }

    /**
     * Create an instance of {@link ApplicationUserGroup }
     * 
     */
    public ApplicationUserGroup createApplicationUserGroup() {
        return new ApplicationUserGroup();
    }

    /**
     * Create an instance of {@link Resort }
     * 
     */
    public Resort createResort() {
        return new Resort();
    }

    /**
     * Create an instance of {@link UserRightsProfile }
     * 
     */
    public UserRightsProfile createUserRightsProfile() {
        return new UserRightsProfile();
    }

    /**
     * Create an instance of {@link PermissionList }
     * 
     */
    public PermissionList createPermissionList() {
        return new PermissionList();
    }

    /**
     * Create an instance of {@link UserRightItem }
     * 
     */
    public UserRightItem createUserRightItem() {
        return new UserRightItem();
    }

    /**
     * Create an instance of {@link UserRightsList }
     * 
     */
    public UserRightsList createUserRightsList() {
        return new UserRightsList();
    }

    /**
     * Create an instance of {@link ApplicationUserGroupList }
     * 
     */
    public ApplicationUserGroupList createApplicationUserGroupList() {
        return new ApplicationUserGroupList();
    }

    /**
     * Create an instance of {@link UserGroupList }
     * 
     */
    public UserGroupList createUserGroupList() {
        return new UserGroupList();
    }

    /**
     * Create an instance of {@link UserSystemRightsProfile }
     * 
     */
    public UserSystemRightsProfile createUserSystemRightsProfile() {
        return new UserSystemRightsProfile();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link ResortList }
     * 
     */
    public ResortList createResortList() {
        return new ResortList();
    }

    /**
     * Create an instance of {@link UserProfile.AccountLocked }
     * 
     */
    public UserProfile.AccountLocked createUserProfileAccountLocked() {
        return new UserProfile.AccountLocked();
    }

    /**
     * Create an instance of {@link UserProfile.Password }
     * 
     */
    public UserProfile.Password createUserProfilePassword() {
        return new UserProfile.Password();
    }

    /**
     * Create an instance of {@link UserProfile.SecurityQuestion }
     * 
     */
    public UserProfile.SecurityQuestion createUserProfileSecurityQuestion() {
        return new UserProfile.SecurityQuestion();
    }

}
