//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.resvadvanced;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.ResultStatus;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlternateRooms" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}AlternateRooms" minOccurs="0"/>
 *         &lt;element name="Result" type="{http://webservices.micros.com/og/4.3/Common/}ResultStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alternateRooms",
    "result"
})
@XmlRootElement(name = "AlternateRoomsResponse")
public class AlternateRoomsResponse {

    @XmlElement(name = "AlternateRooms")
    protected AlternateRooms alternateRooms;
    @XmlElement(name = "Result", required = true)
    protected ResultStatus result;

    /**
     * Gets the value of the alternateRooms property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateRooms }
     *     
     */
    public AlternateRooms getAlternateRooms() {
        return alternateRooms;
    }

    /**
     * Sets the value of the alternateRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateRooms }
     *     
     */
    public void setAlternateRooms(AlternateRooms value) {
        this.alternateRooms = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link ResultStatus }
     *     
     */
    public ResultStatus getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultStatus }
     *     
     */
    public void setResult(ResultStatus value) {
        this.result = value;
    }

}
