//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:53:58 PM IST 
//


package com.micros.webservices.og._4_3.unitowners;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.Amount;
import com.micros.webservices.og._4_3.hotelcommon.TimeSpan;


/**
 * <p>Java class for ContractRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractRestriction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecordId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RestrictionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Dates" type="{http://webservices.micros.com/og/4.3/HotelCommon/}TimeSpan" minOccurs="0"/>
 *         &lt;element name="MaximumNights" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MinimumRate" type="{http://webservices.micros.com/og/4.3/Common/}Amount" minOccurs="0"/>
 *         &lt;element name="UsedNights" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ParentId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Day1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Day7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SystemStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdjustmentReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompNights" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="OwnerMaximum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="AuthMaximum" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="AdjustmentValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Rate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Owner"/>
 *             &lt;enumeration value="AuthorizedUser"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="restriction">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="BlackOut"/>
 *             &lt;enumeration value="AdvanceBooking"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractRestriction", propOrder = {
    "recordId",
    "restrictionType",
    "dates",
    "maximumNights",
    "minimumRate",
    "usedNights",
    "parentId",
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "systemStatus",
    "adjustmentReason",
    "compNights",
    "ownerMaximum",
    "authMaximum",
    "adjustmentValue",
    "rate"
})
public class ContractRestriction {

    @XmlElement(name = "RecordId")
    protected Long recordId;
    @XmlElement(name = "RestrictionType")
    protected String restrictionType;
    @XmlElement(name = "Dates")
    protected TimeSpan dates;
    @XmlElement(name = "MaximumNights")
    protected BigInteger maximumNights;
    @XmlElement(name = "MinimumRate")
    protected Amount minimumRate;
    @XmlElement(name = "UsedNights")
    protected BigInteger usedNights;
    @XmlElement(name = "ParentId")
    protected Long parentId;
    @XmlElement(name = "Day1")
    protected String day1;
    @XmlElement(name = "Day2")
    protected String day2;
    @XmlElement(name = "Day3")
    protected String day3;
    @XmlElement(name = "Day4")
    protected String day4;
    @XmlElement(name = "Day5")
    protected String day5;
    @XmlElement(name = "Day6")
    protected String day6;
    @XmlElement(name = "Day7")
    protected String day7;
    @XmlElement(name = "SystemStatus")
    protected String systemStatus;
    @XmlElement(name = "AdjustmentReason")
    protected String adjustmentReason;
    @XmlElement(name = "CompNights")
    protected BigInteger compNights;
    @XmlElement(name = "OwnerMaximum")
    protected Double ownerMaximum;
    @XmlElement(name = "AuthMaximum")
    protected Double authMaximum;
    @XmlElement(name = "AdjustmentValue")
    protected Double adjustmentValue;
    @XmlElement(name = "Rate")
    protected Double rate;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "restriction")
    protected String restriction;

    /**
     * Gets the value of the recordId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * Sets the value of the recordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRecordId(Long value) {
        this.recordId = value;
    }

    /**
     * Gets the value of the restrictionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictionType() {
        return restrictionType;
    }

    /**
     * Sets the value of the restrictionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictionType(String value) {
        this.restrictionType = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setDates(TimeSpan value) {
        this.dates = value;
    }

    /**
     * Gets the value of the maximumNights property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaximumNights() {
        return maximumNights;
    }

    /**
     * Sets the value of the maximumNights property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaximumNights(BigInteger value) {
        this.maximumNights = value;
    }

    /**
     * Gets the value of the minimumRate property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getMinimumRate() {
        return minimumRate;
    }

    /**
     * Sets the value of the minimumRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setMinimumRate(Amount value) {
        this.minimumRate = value;
    }

    /**
     * Gets the value of the usedNights property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUsedNights() {
        return usedNights;
    }

    /**
     * Sets the value of the usedNights property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUsedNights(BigInteger value) {
        this.usedNights = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setParentId(Long value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the day1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay1() {
        return day1;
    }

    /**
     * Sets the value of the day1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay1(String value) {
        this.day1 = value;
    }

    /**
     * Gets the value of the day2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay2() {
        return day2;
    }

    /**
     * Sets the value of the day2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay2(String value) {
        this.day2 = value;
    }

    /**
     * Gets the value of the day3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay3() {
        return day3;
    }

    /**
     * Sets the value of the day3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay3(String value) {
        this.day3 = value;
    }

    /**
     * Gets the value of the day4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay4() {
        return day4;
    }

    /**
     * Sets the value of the day4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay4(String value) {
        this.day4 = value;
    }

    /**
     * Gets the value of the day5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay5() {
        return day5;
    }

    /**
     * Sets the value of the day5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay5(String value) {
        this.day5 = value;
    }

    /**
     * Gets the value of the day6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay6() {
        return day6;
    }

    /**
     * Sets the value of the day6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay6(String value) {
        this.day6 = value;
    }

    /**
     * Gets the value of the day7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDay7() {
        return day7;
    }

    /**
     * Sets the value of the day7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDay7(String value) {
        this.day7 = value;
    }

    /**
     * Gets the value of the systemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemStatus() {
        return systemStatus;
    }

    /**
     * Sets the value of the systemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemStatus(String value) {
        this.systemStatus = value;
    }

    /**
     * Gets the value of the adjustmentReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentReason() {
        return adjustmentReason;
    }

    /**
     * Sets the value of the adjustmentReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentReason(String value) {
        this.adjustmentReason = value;
    }

    /**
     * Gets the value of the compNights property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompNights() {
        return compNights;
    }

    /**
     * Sets the value of the compNights property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompNights(BigInteger value) {
        this.compNights = value;
    }

    /**
     * Gets the value of the ownerMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOwnerMaximum() {
        return ownerMaximum;
    }

    /**
     * Sets the value of the ownerMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOwnerMaximum(Double value) {
        this.ownerMaximum = value;
    }

    /**
     * Gets the value of the authMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAuthMaximum() {
        return authMaximum;
    }

    /**
     * Sets the value of the authMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAuthMaximum(Double value) {
        this.authMaximum = value;
    }

    /**
     * Gets the value of the adjustmentValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdjustmentValue() {
        return adjustmentValue;
    }

    /**
     * Sets the value of the adjustmentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdjustmentValue(Double value) {
        this.adjustmentValue = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRate(Double value) {
        this.rate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestriction() {
        return restriction;
    }

    /**
     * Sets the value of the restriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestriction(String value) {
        this.restriction = value;
    }

}
