//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:43:24 PM IST 
//


package com.micros.webservices.og._4_3.guestservices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoomStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoomStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Clean"/>
 *     &lt;enumeration value="Dirty"/>
 *     &lt;enumeration value="Inspected"/>
 *     &lt;enumeration value="Pickup"/>
 *     &lt;enumeration value="OutOfOrder"/>
 *     &lt;enumeration value="OutOfService"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoomStatusType")
@XmlEnum
public enum RoomStatusType {

    @XmlEnumValue("Clean")
    CLEAN("Clean"),
    @XmlEnumValue("Dirty")
    DIRTY("Dirty"),
    @XmlEnumValue("Inspected")
    INSPECTED("Inspected"),
    @XmlEnumValue("Pickup")
    PICKUP("Pickup"),
    @XmlEnumValue("OutOfOrder")
    OUT_OF_ORDER("OutOfOrder"),
    @XmlEnumValue("OutOfService")
    OUT_OF_SERVICE("OutOfService");
    private final String value;

    RoomStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoomStatusType fromValue(String v) {
        for (RoomStatusType c: RoomStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
