//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 10:00:49 AM IST 
//


package com.micros.webservices.og._4_3.reservation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.micros.webservices.og._4_3.reservation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.micros.webservices.og._4_3.reservation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HotelReservationList }
     * 
     */
    public HotelReservationList createHotelReservationList() {
        return new HotelReservationList();
    }

    /**
     * Create an instance of {@link ExternalReference }
     * 
     */
    public ExternalReference createExternalReference() {
        return new ExternalReference();
    }

    /**
     * Create an instance of {@link BillHeader }
     * 
     */
    public BillHeader createBillHeader() {
        return new BillHeader();
    }

    /**
     * Create an instance of {@link UpgradeRoom }
     * 
     */
    public UpgradeRoom createUpgradeRoom() {
        return new UpgradeRoom();
    }

    /**
     * Create an instance of {@link BillItem }
     * 
     */
    public BillItem createBillItem() {
        return new BillItem();
    }

    /**
     * Create an instance of {@link MoreFields }
     * 
     */
    public MoreFields createMoreFields() {
        return new MoreFields();
    }

    /**
     * Create an instance of {@link ShareAction }
     * 
     */
    public ShareAction createShareAction() {
        return new ShareAction();
    }

    /**
     * Create an instance of {@link com.micros.webservices.og._4_3.reservation.HotelReservation }
     * 
     */
    public com.micros.webservices.og._4_3.reservation.HotelReservation createHotelReservation() {
        return new com.micros.webservices.og._4_3.reservation.HotelReservation();
    }

    /**
     * Create an instance of {@link BookingRequest }
     * 
     */
    public BookingRequest createBookingRequest() {
        return new BookingRequest();
    }

    /**
     * Create an instance of {@link ReservationGuarantee }
     * 
     */
    public ReservationGuarantee createReservationGuarantee() {
        return new ReservationGuarantee();
    }

    /**
     * Create an instance of {@link UpsellRoomList }
     * 
     */
    public UpsellRoomList createUpsellRoomList() {
        return new UpsellRoomList();
    }

    /**
     * Create an instance of {@link ShareReservationList }
     * 
     */
    public ShareReservationList createShareReservationList() {
        return new ShareReservationList();
    }

    /**
     * Create an instance of {@link ReservationVoucherList }
     * 
     */
    public ReservationVoucherList createReservationVoucherList() {
        return new ReservationVoucherList();
    }

    /**
     * Create an instance of {@link CreditCardSurcharge }
     * 
     */
    public CreditCardSurcharge createCreditCardSurcharge() {
        return new CreditCardSurcharge();
    }

    /**
     * Create an instance of {@link Joiner }
     * 
     */
    public Joiner createJoiner() {
        return new Joiner();
    }

    /**
     * Create an instance of {@link BookingResult }
     * 
     */
    public BookingResult createBookingResult() {
        return new BookingResult();
    }

    /**
     * Create an instance of {@link BillTax }
     * 
     */
    public BillTax createBillTax() {
        return new BillTax();
    }

    /**
     * Create an instance of {@link ShareReservation }
     * 
     */
    public ShareReservation createShareReservation() {
        return new ShareReservation();
    }

    /**
     * Create an instance of {@link ResGuest }
     * 
     */
    public ResGuest createResGuest() {
        return new ResGuest();
    }

    /**
     * Create an instance of {@link WrittenConfInst }
     * 
     */
    public WrittenConfInst createWrittenConfInst() {
        return new WrittenConfInst();
    }

    /**
     * Create an instance of {@link ResGuestList }
     * 
     */
    public ResGuestList createResGuestList() {
        return new ResGuestList();
    }

    /**
     * Create an instance of {@link FetchBookingFilters }
     * 
     */
    public FetchBookingFilters createFetchBookingFilters() {
        return new FetchBookingFilters();
    }

    /**
     * Create an instance of {@link Alert }
     * 
     */
    public Alert createAlert() {
        return new Alert();
    }

    /**
     * Create an instance of {@link UpgradeRoomList }
     * 
     */
    public UpgradeRoomList createUpgradeRoomList() {
        return new UpgradeRoomList();
    }

    /**
     * Create an instance of {@link UpsellRoom }
     * 
     */
    public UpsellRoom createUpsellRoom() {
        return new UpsellRoom();
    }

    /**
     * Create an instance of {@link ReservationVoucher }
     * 
     */
    public ReservationVoucher createReservationVoucher() {
        return new ReservationVoucher();
    }

    /**
     * Create an instance of {@link HotelReservationList.HotelReservation }
     * 
     */
    public HotelReservationList.HotelReservation createHotelReservationListHotelReservation() {
        return new HotelReservationList.HotelReservation();
    }

}
