//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:53:58 PM IST 
//


package com.micros.webservices.og._4_3.hotelcommon;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrencyExchangeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurrencyExchangeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="POSTING"/>
 *     &lt;enumeration value="EXCHANGE"/>
 *     &lt;enumeration value="TA_COMMISSION"/>
 *     &lt;enumeration value="FORECAST"/>
 *     &lt;enumeration value="SETTLEMENT"/>
 *     &lt;enumeration value="EXCHANGE_CHECK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CurrencyExchangeType")
@XmlEnum
public enum CurrencyExchangeType {

    POSTING,
    EXCHANGE,
    TA_COMMISSION,
    FORECAST,
    SETTLEMENT,
    EXCHANGE_CHECK;

    public String value() {
        return name();
    }

    public static CurrencyExchangeType fromValue(String v) {
        return valueOf(v);
    }

}
