//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 04:53:58 PM IST 
//


package com.micros.webservices.og._4_3.hotelcommon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.micros.webservices.og._4_3.common.DescriptiveText;
import com.micros.webservices.og._4_3.common.InternalID;


/**
 * <p>Java class for Note complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Note">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoteText" type="{http://webservices.micros.com/og/4.3/Common/}DescriptiveText"/>
 *         &lt;element name="NoteID" type="{http://webservices.micros.com/og/4.3/Common/}InternalID" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="noteTitle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="internalNote" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Note", propOrder = {
    "noteText",
    "noteID"
})
public class Note {

    @XmlElement(name = "NoteText", required = true)
    protected DescriptiveText noteText;
    @XmlElement(name = "NoteID")
    protected InternalID noteID;
    @XmlAttribute(name = "noteTitle", required = true)
    protected String noteTitle;
    @XmlAttribute(name = "internalNote", required = true)
    protected boolean internalNote;

    /**
     * Gets the value of the noteText property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveText }
     *     
     */
    public DescriptiveText getNoteText() {
        return noteText;
    }

    /**
     * Sets the value of the noteText property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveText }
     *     
     */
    public void setNoteText(DescriptiveText value) {
        this.noteText = value;
    }

    /**
     * Gets the value of the noteID property.
     * 
     * @return
     *     possible object is
     *     {@link InternalID }
     *     
     */
    public InternalID getNoteID() {
        return noteID;
    }

    /**
     * Sets the value of the noteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalID }
     *     
     */
    public void setNoteID(InternalID value) {
        this.noteID = value;
    }

    /**
     * Gets the value of the noteTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteTitle() {
        return noteTitle;
    }

    /**
     * Sets the value of the noteTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteTitle(String value) {
        this.noteTitle = value;
    }

    /**
     * Gets the value of the internalNote property.
     * 
     */
    public boolean isInternalNote() {
        return internalNote;
    }

    /**
     * Sets the value of the internalNote property.
     * 
     */
    public void setInternalNote(boolean value) {
        this.internalNote = value;
    }

}
